run:
  go: 1.18

linters:
  enable-all: true
  disable:
    - gochecknoinits
    - ireturn
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - testpackage
