name: Golangci-Lint

on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.38
